cart/urls.py
from django.urls import path

from . import views


app_name = 'cart'
urlpatterns = [
	path('', views.detail, name='detail'),
	path('add/<int:product_id>/', views.cart_add, name='cart_add'),
	path('remove/<int:product_id>/', views.cart_remove, 
		name='cart_remove'
	),
	
]

shop/urls.py
from django.urls import path

from . import views


app_name='shop'

urlpatterns = [
	path('', views.home, name='home'),
	path('category/<slug:slug>/', views.home, name='category_filter'),
	path('<slug:slug>/', views.product_detail, name='product_detail'),
]

shop_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('orders.urls', namespace='orders')),
    path('', include('shop.urls', namespace='shop')),
] 

shop/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
	sub_category = models.ForeignKey('self', on_delete=models.CASCADE,
		related_name='scategory', null=True, blank=True,
	)
	is_sub = models.BooleanField(default=False)
	name = models.CharField(max_length=200)
	slug = models.SlugField(max_length=200, unique=True)
	
	class Meta:
		ordering = ('name',)
		verbose_name_plural = 'Categories'
	
	def __str__(self):
		return self.name
	
	def get_absolute_url(self):
		return reverse('shop:category_filter', args=[self.slug])


class Product(models.Model):
	category = models.ManyToManyField(
		Category, related_name='products'
	)
	name = models.CharField(max_length=200)
	slug = models.CharField(max_length=200, unique=True)
	image = models.ImageField(upload_to='products/%Y/%m/%d/')
	description = models.TextField()
	price = models.IntegerField()
	available = models.BooleanField(default=True)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	
	class Meta:
		ordering = ('name',)
		
	def __str__(self):
		return self.name
	
	def get_absolute_url(self):
		return reverse('shop:product_detail', args=[self.slug])
		

shop/views.py
from django.shortcuts import render, get_object_or_404

from .models import Category, Product
from cart.forms import CartAddForm


def home(request, slug=None):
	products = Product.objects.filter(available=True)
	categories = Category.objects.filter(is_sub=False)
	
	if slug:
		category = get_object_or_404(Category, slug=slug)
		products = products.filter(category=category)
		
	return render(request, 'shop/home.html', {
		'products': products, 'categories': categories
	})
	

def product_detail(request, slug):
	product = get_object_or_404(Product, slug=slug)
	form = CartAddForm()
	return render(request, 'shop/product_detail.html', 
		{'product': product, 'form': form},
	)

shop/templates/shop/home.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block content %}
  {% for category in categories %}
    <div class="btn-group">
      <button type="button" class="btn btn-danger">{{ category.name }}</button>
      <button type="button" class="btn btn-danger dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <span class="sr-only">Toggle Dropdown</span>
      </button>
      <div class="dropdown-menu">
		  {% for sub in category.scategory.all %}
		    <a class="dropdown-item" href="{{ sub.get_absolute_url }}">{{ sub.name }}</a>
		  {% endfor %}
      </div>
    </div>
  {% endfor %}</br></br>
  {% for product in products %}
    <div class="card" style="width: 18rem; display:inline_block;">
	  {% thumbnail product.image "300x300" crop="center" as im %}
        <img src="{{ im.url }}" class="card-img-top" alt="...">
      {% endthumbnail %}
      <div class="card-body">
        <a href="{{ product.get_absolute_url }}" class="card-title">{{ product.name }}</a>
      </div>
    </div>
  {% endfor %}
{% endblock %}

shop/templates/shop/product_detail.html
{% extends 'base.html' %}

{% block content %}
  <h3>{{ product.name }}</h3>
  <small>{{ product.created }}</small><p>{{ product.price }} $</p></br>
  <img src="{{ product.image.url }}" height="200" width="200" >
  <p>{{ product.description }}</p></br></br>
  <form action="{% url 'cart:cart_add' product.id %}" method="post">
	  {% csrf_token %}
	  {{ form }}
	  <input type="submit" value="Add to cart">
  </form>
{% endblock %}